### ISSUE TITLE
Redesign the Contact Page

### ISSUE THREAD

**Issue by amitroy-thedev** [RIKI-05/MOMOMIA#141] opened 2022-10-11 11:48 UTC
The contact page is not well designed i'd like to redesign the contact page entirely ..
If possible you can assign this project to me and i'm sure you would love it ..
And label this project as hacktoberfest..
Btw i'm doing 2nd contribution in the same repo will it count as valid hacktoberfest project ??

**Comment by RIKI-05** [comment] 2022-10-11 14:30
@amitroy-thedev 
this project is labelled as hacktoberfest that's why all the PRs are getting counted ... if you're asking to name my project as hacktoberfest I can't do that bcz many repos have got excluded because of this reason

As for the Contact page surely you can work on it and your PR will definitely be counted many of the contributors of this project have contributed more than once

**Comment by azeddine011** [comment] 2022-10-11 16:40
Hi @RIKI-05, can you assign this task to me?

**Comment by amitroy-thedev** [comment] 2022-10-12 15:14
![IMG_20221012_204205](https://user-images.githubusercontent.com/104709542/195381107-126467b0-5ddd-4df9-b637-29fb355cbf47.jpg)
This is the demo design I hope you you like it.. 
It might take some time to code.. 
But I'll pr within 1-2 days

**Comment by amitroy-thedev** [comment] 2022-10-12 15:44
Hey @RIKI-05 
![IMG_20221012_204205](https://user-images.githubusercontent.com/104709542/195388327-676ec80d-95c1-4d48-a0be-9d423bf4c690.jpg)
 This is the demo design I hope you like it.. 
I'll code the design and will send the PR within 1-2 days..

**Comment by kituuu** [comment] 2022-10-12 17:18
S#it, I just sent a PR for Contact US page. 0_0

**Comment by kituuu** [comment] 2022-10-12 17:19
Bro please can you give this task to me, I already made the PR... I was working on this from 4 PM.

**Comment by amitroy-thedev** [comment] 2022-10-12 17:23
And I'm working on it since yesterday

**Comment by kituuu** [comment] 2022-10-12 18:06
Batao na :)

**Comment by RIKI-05** [comment] 2022-10-13 06:36
Yahan to jhagda hogaya 😭 ...don't worry guys @kituuu @amitroy-thedev  ...you can work on it...I'll accept both the PRs...but sadly I'll have to choose the one that resonates more with the theme

**Comment by kituuu** [comment] 2022-10-13 06:38
Are jhagna nhi hai xD It's fine ... maine 6 din pehle git use karna sikha tha ... I don't know ki issues naam ki bhi koi cheez hoti hai .

**Comment by amitroy-thedev** [comment] 2022-10-13 08:31
Hello @RIKI-05 i'm having problem
see the screenshot please help to solve it
![Screenshot 2022-10-13 135945](https://user-images.githubusercontent.com/104709542/195544795-74ebcebf-6ef3-4f4d-9de0-5a616bad2fa0.png)
commited twice please guide me how to revert one or do i send the pull request

**Comment by kituuu** [comment] 2022-10-13 12:14
If u send PR it will have the changes caused by the latest commit ... Do you want to send PR with an old commit ??

**Comment by amitroy-thedev** [comment] 2022-10-13 12:21
@kituuu all commits have the same changes

**Comment by kituuu** [comment] 2022-10-13 12:27
Fir koi dikkat nhi hai ... PR bhej do ...But still if you 
Option 1: want to merge them 
Use: 
git log
-> copy commit code of 1st commit (jo commit merge karna hai uske neeche wale commit ka code)
git rebase -i <commit code of 1st>
Fir ek file open honge usme 2 commit aa rahe honge ... Aur dono ke aage 'pick' likha hoga ... 
Pick commit 1
Pick commit 2
Isko aise kar dena
Pick commit 1
s commit 2
... Isse merge ho jayneg

Option 2: want to remove commit
git reset <previous commit code>

I m also inexperienced so kindly take backup first xD

**Comment by amitroy-thedev** [comment] 2022-10-13 12:35
@kituuu I've send the pr.. Thanks let's kya hota hai

**Closed** 2022-10-13 14:52 UTC
Labels: enhancement, good first issue, hacktoberfest

**Comment by kituuu** [comment] 2022-10-13 15:54
Do you have any unpushed commits?

**Comment by amitroy-thedev** [comment] 2022-10-13 18:41
Idk

**Comment by amitroy-thedev** [comment] 2022-10-13 18:42
I don't think so
